### ISSUE TITLE
Better readme would be nice

### ISSUE THREAD

**Issue by manuakasam** [lisachenko/zf2-aspect#1]
Hey there,

would have loved to mess around with this a bit, sadly though it won't run. Initiating the DemoAspects through the init_aspect.php currently results in the error:

```
Class 'Go\Instrument\PathResolver' not found in 
/vendor/lisachenko/go-aop-php/src/Go/Core/AspectKernel.php on line 179
```

I don't really know where to start looking as the DemoAspectKernel adds composers autoloader (through init_autoloader.php) and the namespaces for the GO Autoloader are just as inside your module.

I'm certainly doing something wrong and may be blind right now but i cant figure this out so any help / docs for zf2-implementation would be greatly appreciated. Quick steps would be more than enough, I'll gladly beautify this for your repo once i got it running ;)

**Comment by johnlhon21** [comment]
Is there anything step on how to apply this in Codeigniter.. Thanks in Advance
